repos:
  - repo: local
    hooks:
      - id: hatch-format
        name: Format code
        entry: hatch fmt --formatter
        language: python
        additional_dependencies:
          - hatch>=1.0.0,<2.0.0
        env:
          HATCH_DATA_DIR: .hatch-data/pre-commit
          HATCH_CACHE_DIR: .hatch-data/pre-commit/cache
          HATCH_CONFIG: .hatch-home/config.toml
          UV_CACHE_DIR: .hatch-data/pre-commit/uv-cache
        pass_filenames: false
        types: [python]
        stages: [pre-commit]
      - id: hatch-lint
        name: Lint code
        entry: hatch fmt --linter
        language: python
        additional_dependencies:
          - hatch>=1.0.0,<2.0.0
        env:
          HATCH_DATA_DIR: .hatch-data/pre-commit
          HATCH_CACHE_DIR: .hatch-data/pre-commit/cache
          HATCH_CONFIG: .hatch-home/config.toml
          UV_CACHE_DIR: .hatch-data/pre-commit/uv-cache
        pass_filenames: false
        types: [python]
        stages: [pre-commit]
      - id: hatch-test
        name: Unit tests
        entry: hatch test --cover
        language: python
        additional_dependencies:
          - hatch>=1.0.0,<2.0.0
        env:
          HATCH_DATA_DIR: .hatch-data/pre-commit
          HATCH_CACHE_DIR: .hatch-data/pre-commit/cache
          HATCH_CONFIG: .hatch-home/config.toml
          UV_CACHE_DIR: .hatch-data/pre-commit/uv-cache
        pass_filenames: false
        types: [python]
        stages: [pre-commit]
      - id: commitizen-check
        name: Check commit message
        entry: cz check --commit-msg-file
        language: python
        additional_dependencies:
          - commitizen>=4.4.0,<5.0.0
        stages: [commit-msg]
